# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: students
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo.conf:/etc/mongod.conf.orig:ro
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  # app:
  #   build: ./app
  #   depends_on:
  #     - mongo-express