version: '3.7'
services:
  web:
    build: ./web
    restart: always
    ports:
      - 9000:9000
    environment:
      - DEBUG=0
    depends_on:
      - db

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=market
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
  # postgres_data: