version: '3.7'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 9000:9000
    environment:
      - DEBUG=0
    depends_on:
      - db
  
  # proxy:
  #   image: nginx:1.19.2-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./proxy/conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=market
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
  # postgres_data: