version: '3.7'
services:
  web:
    build: web
    restart: always
    ports:
      - 9000:9000
    environment:
      - DEBUG=0
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=market
    volumes:
      # - db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - flask_network

networks:
  flask_network:

volumes:
  postgres_data: