FROM python:3.8-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app/

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY manage.py .
COPY . .

#CMD python3 manage.py runserver 0.0.0.0:8000
