version: "3.8"
services:
        app:
                build: .
                ports:
                        - "8000:8000"
                image: hacky:1.0
                container_name: app
                env_file:
                        - .env.dev
                command: >
                          sh -c "sleep 7 &&
                                 python manage.py migrate &&
                                 python manage.py runserver 0.0.0.0:8000"
                depends_on:
                        - db

        db:
                image: postgres:11.13-alpine
                volumes:
                        - ./db-data:/var/lib/postgresql/data
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                container_name: db
        