FROM python:3.7.3-slim
ENV PYTHONUNBUFFERED 1
RUN apt update && apt install libpq-dev gcc -y
RUN mkdir /code
WORKDIR /code
COPY requirements-prod.txt /code/
RUN pip install -r requirements-prod.txt
COPY . /code/
CMD gunicorn --bind 0.0.0.0:9000 -w 3 run:app