version: '3.7'

services:
  web:
    image: nginx:1.23.2-alpine
    volumes:
    - ./server1.conf:/etc/nginx/conf.d/default.conf
    - ./templates:/usr/share/nginx/html/
    - ./docs/:/docs/
    - ./nginx.conf://etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80