ARG BaseImage=python
ARG ImageTag=3.7.3
FROM $BaseImage:$ImageTag
ENV PYTHONUNBUFFERED 1
ARG DjangoVersion=3.2.13
ARG GunicornVersion=20.1.0
RUN pip install Django==$DjangoVersion gunicorn==$GunicornVersion
